baseURL: https://liangyi-x.github.io/drunk/
title: 良有以也x
theme: PaperMod
languageCode: 'en'

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: true
paginate: 10
mainsections: ["posts"]

# ---------------------------
# 菜单
# ---------------------------
menu:
  main:
    - name: Archive
      url: /archives
      weight: 5
    - name: Search
      url: /search/
      weight: 10
    - name: Tags
      url: /tags/
      weight: 15
    - name: About
      url: /about/
      weight: 20
    - name: 留言
      url: /posts/example-post/#comments   # 跳到某篇文章的评论区
      weight: 22
    - name: RSS
      url: /index.xml
      weight: 25

# ---------------------------
# 输出
# ---------------------------
outputs:
  home:
    - HTML
    - RSS
    - JSON

# ---------------------------
# 主题参数
# ---------------------------
params:
  showPostExcerpts: true
  summaryLength: 30
  env: production
  author: 霧雨退之.
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false
  hideFooter: false
  ShowLastMod: false

  homeInfoParams:
    Title: "LOST & FOUND"
    Content: 像水消失在水中

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: /archives
      - name: Tags
        url: /tags

  assets:
    disableHLJS: true
    customCSS:
      - "css/extended/magazine.css"

# ---------------------------
# 评论功能
# ---------------------------
comments: true  # 全局开启文章评论
