baseURL: https://liangyi-x.github.io/drunk/
title: 良有以也x
theme: [PaperMod]
languageCode: 'en'

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: true
paginate: 10
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
# relativeURLs: true
mainsections: ["posts"]

minify:
  disableXML: true
  # minifyOutput: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: about
      url: about/
      weight: 20
    - name: RSS
      url: index.xml
      weight: 25

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  showPostExcerpts: true
  summaryLength: 150
  env: production
  description:
  author: 霧雨退之.

  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false
  TocOpen: false
  ShowFullTextinRSS: true
  hideFooter: false
  ShowLastMod: false

  homeInfoParams:
    Title: "LOST & FOUND"
    Content: 像水消失在水中

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  assets:
    disableHLJS: true

  # -------------------------
  # ⭐ 评论功能（新增）
  # -------------------------
  comments: true

  giscus:
    repo: "liangyi-x/drunk"  # 改成你的仓库
    repoID: ""               # 去 giscus.app 生成
    category: "General"
    categoryID: ""           # 去 giscus.app 生成
    mapping: "pathname"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "bottom"
    lang: "zh-CN"
    loading: "lazy"

