baseURL: https://liangyi-x.github.io/drunk/
title: 良有以也x
theme: [PaperMod]
languageCode: 'en'

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
hasCJKLanguage: true
paginate: 10
mainsections: ["posts"]

params:
  showPostExcerpts: true
  summaryLength: 30
  env: production
  author: 霧雨退之.
  defaultTheme: auto
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false
  hideFooter: false
  ShowLastMod: false

  homeInfoParams:
    Title: "LOST & FOUND"
    Content: 像水消失在水中

  assets:
    disableHLJS: true
    customCSS: ["css/extended/magazine.css"]

  # -------------------------
  # 评论功能（Giscus）
  # -------------------------
  comments: true
  giscus:
    repo: "liangyi-x/drunk"
    repoID: "R_kgDOQX6njg"
    category: "Announcements"
    categoryID: "DIC_kwDOQX6njs4CyABK"
    mapping: "pathname"
    reactionsEnabled: "1"
    emitMetadata: "0"
    inputPosition: "bottom"
    lang: "zh-CN"
    loading: "lazy"
